name: screen_capturer_platform_interface
description: A common platform interface for the screen_capturer plugin.
version: 0.2.2
homepage: https://github.com/leanflutter/screen_capturer/blob/main/packages/screen_capturer_platform_interface
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: 
  plugin_platform_interface: ^2.1.8
  screen_retriever:
    git:
      url: https://github.com/xx-deps/screen_retriever.git
      ref: v1.0.3
      path: packages/screen_retriever

dev_dependencies:
  build_runner: 
  flutter_test:
    sdk: flutter
  json_serializable:
  mostly_reasonable_lints: ^0.1.2
